# Generated by Django 5.2.5 on 2025-09-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='updated_at',
        ),
    ]
